[package]
name = "komsi"
version = "0.2.0"
edition = "2024"
description = "Library for th KOMSI protocol"
license = "MIT"
readme = "README.md"
repository = "https://github.com/thatzok/komsi-lib"

[dependencies]


