[package]
name = "komsi"
version = "0.5.0"
edition = "2024"
description = "Library for the KOMSI protocol"
license = "MIT"

readme = "README.md"
repository = "https://github.com/thatzok/komsi-lib"

[dependencies]


